'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contacto
    Public Property IdContacto As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Direccion As String
    Public Property Correo As String

    Public Overridable Property Numeros As ICollection(Of Numeros) = New HashSet(Of Numeros)

End Class
