'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Numeros
    Public Property IdNumero As Integer
    Public Property Numero As String
    Public Property IdOperadora As Nullable(Of Integer)
    Public Property IdContacto As Nullable(Of Integer)

    Public Overridable Property Contacto As Contacto
    Public Overridable Property Operadoras As Operadoras

End Class
